import React, { useState, useEffect } from 'react';
import {
    Box, Typography, Paper, Grid, Card, CardContent, Table, TableBody, TableCell,
    TableContainer, TableHead, TableRow, Chip, LinearProgress, Stack, Divider,
    TextField, Select, MenuItem, FormControl, InputLabel, InputAdornment,
    Button, IconButton
} from '@mui/material';
import TrendingUpIcon from '@mui/icons-material/TrendingUp';
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutline';
import CalculateIcon from '@mui/icons-material/Calculate';
import SearchIcon from '@mui/icons-material/Search';
import SummarizeIcon from '@mui/icons-material/Summarize';
import DownloadIcon from '@mui/icons-material/Download';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import Menu from '@mui/material/Menu';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const AcademicPerformance = () => {
    const [user, setUser] = useState(null);
    const [performance, setPerformance] = useState([]);
    const [gwaData, setGwaData] = useState(null);
    const [searchQuery, setSearchQuery] = useState('');
    const [filterClass, setFilterClass] = useState('all');
    const [exportAnchorEl, setExportAnchorEl] = useState(null);
    const [selectedReportSection, setSelectedReportSection] = useState(null);

    const handleExportPDF = (section) => {
        const doc = new jsPDF();
        
        // Brand Header
        doc.setFillColor(37, 99, 235);
        doc.rect(0, 0, 210, 40, 'F');
        doc.setFontSize(22);
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'bold');
        doc.text('EDUTRACK STUDENT REPORT', 14, 20);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'normal');
        doc.text('Individual Academic Performance Breakdown', 14, 28);
        
        // Info Section
        doc.setTextColor(30, 41, 59);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(`Subject: ${section.sectionName} (${section.sectionCode})`, 14, 52);
        doc.text(`Student: ${user.name}`, 14, 58);
        
        // 1. Attendance Summary
        doc.setFontSize(11);
        doc.text(`I. ATTENDANCE (Rate: ${section.attendanceRate}%)`, 14, 70);
        autoTable(doc, {
            startY: 73,
            head: [['Date', 'Status']],
            body: (section.attendanceRecords || []).map(r => [r.date, r.status]),
            theme: 'grid',
            headStyles: { fillColor: [37, 99, 235] },
            styles: { halign: 'center' },
            columnStyles: { 0: { halign: 'left' } }
        });

        // 2. Category Summary
        autoTable(doc, {
            startY: doc.lastAutoTable.finalY + 15,
            head: [['Category', 'Weight', 'Average', 'Equivalent']],
            body: Object.entries(section.categoryBreakdown).map(([type, data]) => [
                type, `${data.weight}%`, `${data.average}%`, data.equivalentGrade
            ]),
            theme: 'grid',
            headStyles: { fillColor: [71, 85, 105] },
            styles: { halign: 'center' },
            columnStyles: { 0: { halign: 'left', fontStyle: 'bold' } }
        });

        // 3. Assessment Details
        doc.addPage();
        doc.setFontSize(14);
        doc.text('III. DETAILED ASSESSMENT SCORES', 14, 20);
        autoTable(doc, {
            startY: 25,
            head: [['Assessment Title', 'Score', 'Perfect Score', 'Percentage']],
            body: Object.values(section.categoryBreakdown).flatMap(cat => 
                cat.scores.map(s => [s.title, s.score, s.perfectScore, `${s.percentage}%`])
            ),
            theme: 'grid',
            headStyles: { fillColor: [37, 99, 235] },
            styles: { halign: 'center' },
            columnStyles: { 0: { halign: 'left' } }
        });
        
        // Final Summary Block
        const finalY = doc.lastAutoTable.finalY + 15;
        doc.setFillColor(248, 250, 252);
        doc.rect(14, finalY, 182, 30, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        doc.setTextColor(37, 99, 235);
        doc.text(`FINAL GRADE: ${section.sectionGrade}%`, 20, finalY + 12);
        doc.text(`EQUIVALENT: ${section.equivalentGrade} (${section.gradeDescription})`, 20, finalY + 22);

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`Generated by EduTrack © ${new Date().getFullYear()}`, 14, 285);
        doc.save(`${user.name}_${section.sectionCode}_Report.pdf`);
    };

    const handleExportCSV = (section) => {
        let rows = [];
        
        // 1. Attendance
        rows.push(['I. ATTENDANCE REPORT', `Rate: ${section.attendanceRate}%`]);
        rows.push(['Date', 'Status']);
        (section.attendanceRecords || []).forEach(r => rows.push([r.date, r.status]));
        rows.push([]);

        // 2. Categories
        rows.push(['II. CATEGORY SUMMARY']);
        rows.push(['Category', 'Weight', 'Average', 'Equivalent']);
        Object.entries(section.categoryBreakdown).forEach(([type, data]) => {
            rows.push([type, `${data.weight}%`, `${data.average}%`, data.equivalentGrade]);
        });
        rows.push([]);

        // 3. Assessment Scores
        rows.push(['III. DETAILED SCORES']);
        rows.push(['Assessment Title', 'Score', 'Perfect Score', 'Percentage']);
        Object.values(section.categoryBreakdown).forEach(cat => {
            cat.scores.forEach(s => rows.push([s.title, s.score, s.perfectScore, `${s.percentage}%`]));
        });
        rows.push([]);

        // 4. Final
        rows.push(['FINAL GRADE', `${section.sectionGrade}%`]);
        rows.push(['EQUIVALENT', section.equivalentGrade]);
        rows.push(['REMARKS', section.gradeDescription]);
        
        const csvContent = rows.map(r => r.map(cell => `"${(cell || '').toString().replace(/"/g, '""')}"`).join(',')).join('\n');
        const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        link.setAttribute('href', URL.createObjectURL(blob));
        link.setAttribute('download', `${user.name}_${section.sectionCode}_Detailed_Report.csv`);
        link.click();
    };

    useEffect(() => {
        try {
            const stored = localStorage.getItem('user');
            if (stored) setUser(JSON.parse(stored));
        } catch (e) { console.error('Failed to parse user', e); }
    }, []);

    const fetchPerformance = async () => {
        const token = localStorage.getItem('token');
        try {
            const res = await fetch(`/api/student/${user?.id}/performance`, {
                headers: { 'Authorization': `Bearer ${token}` }
            });
            if (res.ok) {
                const data = await res.json();
                if (Array.isArray(data)) setPerformance(data);
            }
        } catch (err) { console.error('Performance fetch failed', err); }
    };

    const fetchGWA = async () => {
        const token = localStorage.getItem('token');
        try {
            const res = await fetch(`/api/student/${user?.id}/gwa`, {
                headers: { 'Authorization': `Bearer ${token}` }
            });
            if (res.ok) {
                const data = await res.json();
                setGwaData(data);
            }
        } catch (err) { console.error('GWA fetch failed', err); }
    };


    useEffect(() => {
        if (user?.id) {
            fetchPerformance();
            fetchGWA();
        }
    }, [user?.id]);

    const gradeColor = (gwaData?.gwa || 0) >= 85 ? '#16A34A' : (gwaData?.gwa || 0) >= 75 ? '#2563EB' : '#DC2626';

    const filteredSections = (gwaData?.sectionGrades || []).filter(s => 
        filterClass === 'all' || s.sectionId === filterClass
    );

    const filteredPerformance = performance.filter(p => {
        const matchesClass = filterClass === 'all' || p.section_id === filterClass;
        const matchesSearch = p.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
                             p.sectionName.toLowerCase().includes(searchQuery.toLowerCase());
        return matchesClass && matchesSearch;
    });

    return (
        <Box sx={{ p: 4, bgcolor: '#f8fafc', minHeight: '100vh' }}>
            <Box sx={{ mb: 4 }}>
                <Typography variant="h4" fontWeight={800} sx={{ letterSpacing: '-0.5px' }}>
                    My Academic Performance
                </Typography>
                <Typography variant="body1" color="text.secondary">
                    Comprehensive GWA breakdown and assessment history.
                </Typography>
            </Box>

            {/* Filters */}
            <Paper elevation={0} sx={{ p: 3, mb: 4, border: '1px solid', borderColor: 'divider', borderRadius: 4 }}>
                <Grid container spacing={2} alignItems="center">
                    <Grid size={{ xs: 12, md: 4 }}>
                        <FormControl fullWidth size="small">
                            <InputLabel sx={{ fontWeight: 600 }}>Filter by Class</InputLabel>
                            <Select
                                value={filterClass}
                                label="Filter by Class"
                                onChange={(e) => setFilterClass(e.target.value)}
                                sx={{ borderRadius: 2, fontWeight: 700 }}
                            >
                                <MenuItem value="all" sx={{ fontWeight: 700 }}>All Enrolled Classes</MenuItem>
                                {(gwaData?.sectionGrades || []).map(s => (
                                    <MenuItem key={s.sectionId} value={s.sectionId} sx={{ fontWeight: 700 }}>
                                        {s.sectionName} ({s.sectionCode})
                                    </MenuItem>
                                ))}
                            </Select>
                        </FormControl>
                    </Grid>
                    <Grid size={{ xs: 12, md: 8 }}>
                        <TextField
                            fullWidth
                            size="small"
                            placeholder="Search assessments by name or section..."
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            InputProps={{
                                startAdornment: <InputAdornment position="start"><SearchIcon sx={{ color: 'text.secondary' }} /></InputAdornment>,
                                sx: { borderRadius: 2 }
                            }}
                        />
                    </Grid>
                </Grid>
            </Paper>

            <Grid container spacing={3}>
                {/* GWA Summary Card */}
                <Grid size={{ xs: 12, md: 4 }}>
                    <Card elevation={0} sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 5, height: '100%' }}>
                        <CardContent sx={{ p: 4 }}>
                            <Stack direction="row" spacing={2} alignItems="center" mb={2}>
                                <Box sx={{ p: 1.5, borderRadius: 2, bgcolor: `${gradeColor}10`, color: gradeColor }}>
                                    <TrendingUpIcon />
                                </Box>
                                <Typography variant="h6" fontWeight={700}>Overall GWA</Typography>
                            </Stack>
                            <Typography variant="h2" fontWeight={900} sx={{ color: gradeColor }}>
                                {gwaData?.equivalentGrade || '—'}
                            </Typography>
                            <Stack direction="row" spacing={1} alignItems="baseline" sx={{ mt: 1 }}>
                                <Typography variant="h5" fontWeight={800}>
                                    {gwaData?.gwa || 0}%
                                </Typography>
                                <Typography variant="body2" color="text.secondary" fontWeight={600}>
                                    ({gwaData?.gradeDescription || 'N/A'})
                                </Typography>
                            </Stack>
                            <LinearProgress variant="determinate" value={gwaData?.gwa || 0}
                                sx={{
                                    height: 10, borderRadius: 5, mt: 3, bgcolor: `${gradeColor}20`,
                                    '& .MuiLinearProgress-bar': { bgcolor: gradeColor }
                                }} />
                        </CardContent>
                    </Card>
                </Grid>

                {/* GWA Formula & Category Breakdown */}
                <Grid size={{ xs: 12, md: 8 }}>
                    <Card elevation={0} sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 5, height: '100%' }}>
                        <CardContent sx={{ p: 4 }}>
                            <Stack direction="row" spacing={1} alignItems="center" mb={2}>
                                <CalculateIcon sx={{ color: '#2563EB' }} />
                                <Typography variant="h6" fontWeight={800}>GWA Breakdown</Typography>
                            </Stack>

                            <Box sx={{ maxHeight: 260, overflowY: 'auto', pr: 1, '&::-webkit-scrollbar': { width: '6px' }, '&::-webkit-scrollbar-thumb': { bgcolor: '#e2e8f0', borderRadius: '10px' } }}>
                            {filteredSections.map((section, idx) => (
                                <Box key={idx} sx={{ mb: 2, p: 2, border: '1px solid', borderColor: 'divider', borderRadius: 3, bgcolor: '#f8fafc' }}>
                                    <Stack direction="row" justifyContent="space-between" alignItems="flex-start" mb={2}>
                                        <Box>
                                            <Typography variant="subtitle1" fontWeight={800} color="primary">
                                                {section.sectionName}
                                                <Chip label={section.sectionCode} size="small" sx={{ ml: 1, fontWeight: 700, fontSize: '0.65rem' }} />
                                            </Typography>
                                            <Typography variant="caption" color="text.secondary" fontWeight={700}>
                                                Status: <Chip label={section.sectionStatus?.toUpperCase() || 'ACTIVE'} size="small" variant="outlined" 
                                                    sx={{ height: 18, fontSize: '0.6rem', fontWeight: 900, color: section.sectionStatus === 'completed' ? '#16a34a' : '#2563eb' }} />
                                            </Typography>
                                        </Box>
                                        <Stack spacing={1} alignItems="flex-end">
                                            <Stack direction="row" spacing={1}>
                                                <Chip label={section.equivalentGrade} color={section.sectionGrade >= 75 ? 'primary' : 'error'} sx={{ fontWeight: 800 }} />
                                                <Chip label={`${section.sectionGrade}%`} variant="outlined" size="small" sx={{ fontWeight: 700, fontSize: '0.7rem' }} />
                                            </Stack>
                                            
                                            {/* Report Export Dropdown for Finished Classes */}
                                            {section.sectionStatus === 'completed' && (
                                                <Box>
                                                    <Button 
                                                        size="small" 
                                                        variant="contained" 
                                                        startIcon={<SummarizeIcon />} 
                                                        endIcon={<KeyboardArrowDownIcon />}
                                                        onClick={(e) => {
                                                            setExportAnchorEl(e.currentTarget);
                                                            setSelectedReportSection(section);
                                                        }}
                                                        sx={{ fontWeight: 700, fontSize: '0.65rem', borderRadius: 1, bgcolor: '#2563eb' }}
                                                    >
                                                        Get Report
                                                    </Button>
                                                    <Menu
                                                        anchorEl={exportAnchorEl}
                                                        open={Boolean(exportAnchorEl)}
                                                        onClose={() => setExportAnchorEl(null)}
                                                        PaperProps={{ sx: { borderRadius: 2, minWidth: 150, mt: 1 } }}
                                                    >
                                                        <MenuItem onClick={() => { handleExportPDF(selectedReportSection); setExportAnchorEl(null); }} sx={{ fontWeight: 600, fontSize: '0.8rem' }}>PDF Breakdown</MenuItem>
                                                        <MenuItem onClick={() => { handleExportCSV(selectedReportSection); setExportAnchorEl(null); }} sx={{ fontWeight: 600, fontSize: '0.8rem' }}>CSV Breakdown</MenuItem>
                                                    </Menu>
                                                </Box>
                                            )}
                                        </Stack>
                                    </Stack>

                                    {/* Category averages */}
                                    <Stack spacing={2}>
                                        {Object.entries(section.categoryBreakdown).map(([type, data]) => (
                                            <Box key={type}>
                                                <Stack direction="row" justifyContent="space-between" alignItems="center">
                                                    <Typography variant="body2" fontWeight={700}>
                                                        {type} <Typography component="span" variant="caption" color="text.secondary">({data.weight}% weight)</Typography>
                                                    </Typography>
                                                    <Typography variant="body2" fontWeight={800} color={data.average >= 75 ? 'success.main' : 'error.main'}>
                                                        {data.equivalentGrade} <Typography component="span" variant="caption" color="text.secondary" sx={{ ml: 0.5 }}>({data.average}%)</Typography>
                                                    </Typography>
                                                </Stack>
                                                <LinearProgress variant="determinate" value={data.average}
                                                    sx={{
                                                        height: 6, borderRadius: 3, mt: 0.5,
                                                        bgcolor: '#e2e8f0',
                                                        '& .MuiLinearProgress-bar': {
                                                            bgcolor: type === 'Major Exams' ? '#2563EB' : type === 'Performance Tasks' ? '#7C3AED' : '#059669'
                                                        }
                                                    }} />
                                            </Box>
                                        ))}
                                    </Stack>

                                    {idx < (gwaData?.sectionGrades?.length || 0) - 1 && <Divider sx={{ mt: 3 }} />}
                                </Box>
                            ))}
                            </Box>

                        </CardContent>
                    </Card>
                </Grid>
                {/* Assessment History Table */}
                <Grid size={{ xs: 12 }}>
                    <TableContainer component={Paper} elevation={0} sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 5, p: 2 }}>
                        <Table>
                            <TableHead sx={{ bgcolor: '#f8fafc' }}>
                                <TableRow>
                                    <TableCell sx={{ fontWeight: 700 }}>Assessment</TableCell>
                                    <TableCell sx={{ fontWeight: 700 }}>Section</TableCell>
                                    <TableCell sx={{ fontWeight: 700 }}>Category</TableCell>
                                    <TableCell sx={{ fontWeight: 700 }} align="center">Score</TableCell>
                                    <TableCell sx={{ fontWeight: 700 }} align="center">Status</TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {filteredPerformance.map((p) => (
                                    <TableRow key={p.id} hover>
                                        <TableCell sx={{ fontWeight: 600 }}>{p.title}</TableCell>
                                        <TableCell sx={{ color: 'text.secondary' }}>{p.sectionName}</TableCell>
                                        <TableCell>
                                            <Chip label={p.type} size="small" sx={{
                                                fontWeight: 700, borderRadius: 1,
                                                bgcolor: p.type === 'Major Exams' ? '#eff6ff' : p.type === 'Performance Tasks' ? '#f3e8ff' : '#ecfdf5',
                                                color: p.type === 'Major Exams' ? '#2563EB' : p.type === 'Performance Tasks' ? '#7C3AED' : '#059669'
                                            }} />
                                        </TableCell>
                                        <TableCell align="center">
                                            <Typography fontWeight={800}>
                                                {p.achievedScore !== null ? `${p.achievedScore} / ${p.perfectScore}` : '—'}
                                            </Typography>
                                        </TableCell>
                                        <TableCell align="center">
                                            {p.achievedScore !== null ? (
                                                <Chip icon={<CheckCircleOutlineIcon />} label="GRADED" color="success" variant="filled"
                                                    size="small" sx={{ fontWeight: 800, fontSize: '0.65rem' }} />
                                            ) : (
                                                <Typography variant="caption" color="text.secondary" fontWeight={700}>PENDING</Typography>
                                            )}
                                        </TableCell>
                                    </TableRow>
                                ))}
                                {performance.length === 0 && (
                                    <TableRow><TableCell colSpan={5} align="center" sx={{ py: 8 }}>
                                        <Typography color="text.secondary" fontWeight={500}>
                                            No assessments found. They'll appear here once your instructor creates them.
                                        </Typography>
                                    </TableCell></TableRow>
                                )}
                            </TableBody>
                        </Table>
                    </TableContainer>
                </Grid>
            </Grid>
        </Box>
    );
};

export default AcademicPerformance;
